<?php
require_once dirname(__FILE__).'/../../../../Mouf.php';


function druplash_perm() {
  return array('access druplash', 'access admin druplash');
}

/**
 * This is the central hook for druplash.
 * It acts as the controller by binding the paths to the controllers actions.
 * 
 */
function druplash_menu() {
	// Let's find the Drupal Controllers.
	return Druplash::getDrupalMenus();
}

function druplash_execute_action($instanceName, $actionName) {
	return Druplash::executeAction($instanceName, $actionName);
}

/**
 * The hook called to dynamically add blocks to Drupal.
 */
function druplash_block_info() {
	return Druplash::getDrupalBlocks();
}

/**
 * The hook called to dynamically get the content of a block.
 */
function druplash_block_view($delta = '') {
	return Druplash::getDrupalBlock($delta);
}
?>