<?php

/**
 * This class represent a Html Grid (an HTML datagrid).
 *
 * @Component
 */
class HtmlGridWidget extends DataGrid implements HtmlElementInterface {
	
	private static $number = 0;
	
	/**
	 * The ID of the table element that will contain the table.
	 * If none is passed, an ID is autogenerated.
	 *
	 * @Property
	 * @var string
	 */
	public $tableId;
	
	/**
	 * The ID of the div element that will contian the pager.
	 * If none is passed, an ID is autogenerated.
	 *
	 * @Property
	 * @var string
	 */
	public $pagerId;
	
	/**
	 * The URL that will be used to retrieve the data to be displayed.
	 * Path is relative to the ROOT_URL and should not start with a /.
	 *
	 * @Property 
	 * @var string
	 */
	public $dataUrl;
	
	/**
	 * The name of the column which the default sort will be performed on.
	 *
	 * @Property 
	 * @Compulsory
	 * @var string
	 */
	public $defaultSortColumn;
	
	/**
	 * The default sort order (ASC or DESC).
	 *
	 * @Property
	 * @Compulsory
	 * @OneOf("ASC", "DESC")
	 * @var string
	 */
	public $defaultSortOrder = "ASC";
	
	/**
	 * The name of the column which sort is currently performed on.
	 *
	 * @Property 
	 * @Compulsory
	 * @var string
	 */
	private $currentSortColumn;
	
	/**
	 * The current sort order (ASC or DESC).
	 *
	 * @Property
	 * @Compulsory
	 * @OneOf("ASC", "DESC")
	 * @var string
	 */
	private $currentSortOrder;
	
	/**
	 * The caption for the table.
	 * If none is passed, no caption is displayed.
	 *
	 * @Property
	 * @var string
	 */
	public $caption;
	
	/**
	 * The max number of rows displayed
	 * @Compulsory
	 * @var int
	 */
	public $maxDisplay;
	
	/**
	 * The current page
	 *  @var int
	 */
	public $currentPage=1;
	
	
	/**
	 * Renders the object in HTML.
	 * The Html is echoed directly into the output.
	 *
	 */
	function toHtml($page=1, $sortCol=null, $sortOrder=null) {
		self::$number++; 
		$this->currentPage = empty($page)?1:$page;
		$this->currentSortColumn = $sortCol;
		$this->currentSortOrder = $sortOrder;
		
		$this->datasource->setOrderColumn($sortCol);
		$this->datasource->setOrder($sortOrder);
		
//		echo ("Page: $this->currentPage Column: $this->currentSortColumn Order: $this->currentSortOrder");
		

		if ($this->tableId == null) {
			$tableId = "moufJqGridTableNumber".self::$number;
		} else {
			$tableId = $this->tableId;
		}
		
		if ($this->pagerId == null) {
			$pagerId = "moufJqGridPagerNumber".self::$number;
		} else {
			$pagerId = $this->pagerId;
		}
		
		if ($this->currentSortOrder == null) {
			$this->currentSortOrder = $this->defaultSortOrder;
			$this->datasource->setOrder($this->defaultSortOrder);
		}
		if ($this->currentSortColumn == null) {
			$this->currentSortColumn = $this->defaultSortColumn;
			$this->datasource->setOrderColumn($this->defaultSortColumn);
		}
?>
		<table class="ttd" cellpadding="0" cellspacing="0">
		<tbody>
			<tr>
			<?php 
			foreach ($this->columns as $column) {
				if ($this->currentSortColumn==$column->getSortColumn() && $this->currentSortOrder=="ASC"){
					$sortUrl = $this->getSortUrl($column, "DESC");
				}else $sortUrl =  $this->getSortUrl($column, "ASC");
			?>
				<th style="width: <?php echo $column->getWidth()?$column->getWidth()."px":"auto" ?>" <?php if ($column->isSortable()) echo "class='sortable' onclick=\"window.location='$sortUrl'\"" ?>>
					<table><tr>
					<td>
						<?php echo $column->getTitle();
						?>
					</td>
					<td>
					<?php 
					if ($column->isSortable()){
						
					?>
						<?php
						if ($this->currentSortColumn==$column->getSortColumn() && $this->currentSortOrder=="ASC"){
						?>
							<div class="sort asc">&nbsp;</div>
						<?php
						}else{?>
							<div class="sort desc">&nbsp;</div>
						<?php }
					}
					
					?>
					</td>
					</tr></table>
				</th>
			<?php
			}
			?>
			</tr>
			<?php
			$i=0;
			$count = $this->datasource->getGlobalCount();
			// calculate the total pages for the query 
			if( $count > 0 ) { 
				$total_pages = ceil($count/$this->maxDisplay); 
			} else { 
				$total_pages = 0; 
			} 
			// if for some reasons the requested page is greater than the total 
			// set the requested page to total page 
			if ($page > $total_pages) $page=$total_pages;
			 
			// calculate the starting position of the rows 
			$start = $this->maxDisplay*$page - $this->maxDisplay;
			// if for some reasons start position is negative set it to 0 
			// typical case is that the user type 0 for the requested page 
			if($start <0) $start = 0; 
			$this->datasource->load(array(), $start, $this->maxDisplay);
			foreach ($this->datasource as $row){
				$class = ($i%2)?"odd":"even";
				$i++;
			?>
				<tr class="<?php echo $class ?>">
			<?php 
				foreach ($this->columns as $column) {
			?>
					<td><?php echo $column->getValue($row) ?></td>
			<?php
				}
			 ?>
				</tr>
			<?php	
			}?>
			<tr>
				<td class="pager_cell" colspan="<?php echo (count($this->dataModel->dataColumns)+count($this->dataModel->actionColums)) ?>">
					<?php $this->getPaginateHTML($total_pages); ?>
				</td>
			</tr>
		</tbody>
		</table>
		
<?php
	}
	
	function getSortUrl($column, $order){
		return $this->dataUrl."?sort=".$column->getSortColumn()."&order=$order";
	}
	
	function getPaginateUrl($pageNb){
		return $this->dataUrl."?sort=".$this->currentSortColumn."&order=$this->currentSortOrder&page=$pageNb";
	}
	
	public function getPaginateHTML($total_pages){
	?>
		<table class="pager">
			<tr>
				<td class="first_page" onclick="window.location='<?php echo $this->getPaginateUrl(1); ?>'"></td>
			<?php if ($this->currentPage!=1){ ?>
				<td class="previous_page" onclick="window.location='<?php echo $this->getPaginateUrl($this->currentPage-1); ?>'"></td>
			<?php } ?>
				<?php 
				for ($i=1;$i<=$total_pages;$i++){
						if ($i == $this->currentPage){
						?>
							<td class="current_page"><?php echo $i; ?></td>
						<?php
						}
						else{
						?>
							<td class="other_page"><a href="<?php echo $this->getPaginateUrl($i)?>"><?php echo $i; ?></a></td>
						<?php
						}
				}				
				?>
			<?php if ($this->currentPage != $total_pages){ ?>
				<td class="next_page" onclick="window.location='<?php echo $this->getPaginateUrl($this->currentPage+1); ?>'"></td>
			<?php } ?>
				<td class="last_page" onclick="window.location='<?php echo $this->getPaginateUrl($total_pages); ?>'"></td>
			</tr>
		</table>
	<?php
	}
	
}
?>