<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not put any code except 'define' operations
 * as it could be overwritten.
 * Instead, use the Mouf User Interface to set all your constants: http://[server]/mouf/mouf/config
 */

/**
 * If you set this variable to true, your Mouf installation will act as a repository: it will allow other Mouf installations to download any package available.
 * By default, this is behaviour is disabled.
 */
define('ACT_AS_REPOSITORY', true);
