<?php
/**
 * This file is used to install the Mouf framework by creating the .htaccess file.
 */

$uri = $_SERVER["REQUEST_URI"];

$installPos = strpos($uri, "/install.php");
if ($installPos !== FALSE) {
	$uri = substr($uri, 0, $installPos);
}


$str .= "Options FollowSymLinks
RewriteEngine on
RewriteBase $uri

#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule !((\.(js|ico|gif|jpg|png|css)$)|^direct) splash.php";

file_put_contents(".htaccess", $str);


// Now, let's write the basic Mouf files:
// Write Mouf.php:
if (!file_exists("../Mouf.php")) {
	$moufStr = "<?php
	require_once 'MoufComponents.php';
	require_once 'MoufUniversalParameters.php';
	require_once 'MoufRequire.php';
	?>";
	
	file_put_contents("../Mouf.php", $moufStr);
}



// Write MoufComponents.php:
if (!file_exists("../MoufComponents.php")) {
	$moufComponentsStr = "<?php
	/**
	 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
	 */
	require_once 'mouf/MoufManager.php';
	MoufManager::initMoufManager();
	?>";
	
	file_put_contents("../MoufComponents.php", $moufComponentsStr);
}

// Write MoufUniversalParameters.php
if (!file_exists("../MoufUniversalParameters.php")) {
	$uriWithoutMouf = substr($uri, 0, -4);
	$moufUniversalStr = "<?php
	
	define('ROOT_PATH', realpath(dirname(__FILE__)).'/');
	define('ROOT_URL','".$uriWithoutMouf."');
	define('PLUGINS_URL',ROOT_URL.'plugins/');
	?>";
	
	file_put_contents("../MoufUniversalParameters.php", $moufUniversalStr);
}

// Finally, let's generate the MoufRequire.php file:
if (!file_exists("../MoufRequire.php")) {
	$moufRequireStr = "<?php
	/**
	 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
	 */
	
	?>";
	
	file_put_contents("../MoufRequire.php", $moufRequireStr);
}



header("Location: ".$uri."/");

?>