<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

// Packages dependencies
$localFilePath = dirname(__FILE__);
require_once $localFilePath.'/../plugins/utils/log/log_interface/1.0/LogInterface.php';
require_once $localFilePath.'/../plugins/html/htmlelement/1.0/Scopable.php';
require_once $localFilePath.'/../plugins/html/htmlelement/1.0/HtmlElementInterface.php';
require_once $localFilePath.'/../plugins/html/htmlelement/1.0/HtmlFromFile.php';
require_once $localFilePath.'/../plugins/html/htmlelement/1.0/HtmlFromFunction.php';
require_once $localFilePath.'/../plugins/html/htmlelement/1.0/HtmlString.php';
require_once $localFilePath.'/../plugins/html/template/BaseTemplate/1.0/TemplateInterface.php';
require_once $localFilePath.'/../plugins/html/template/BaseTemplate/1.0/BaseTemplate.php';
require_once $localFilePath.'/../plugins/html/template/SplashTemplate/1.0/SplashTemplate.php';
require_once $localFilePath.'/../plugins/html/template/SplashTemplate/1.0/SplashMenu.php';
require_once $localFilePath.'/../plugins/html/template/SplashTemplate/1.0/SplashMenuItem.php';
require_once $localFilePath.'/../plugins/utils/i18n/fine/1.0/MessageFile.php';
require_once $localFilePath.'/../plugins/utils/i18n/fine/1.0/LanguageUtils.php';
require_once $localFilePath.'/../plugins/mvc/splash/1.0/models/Splash.php';
require_once $localFilePath.'/../plugins/javascript/jquery/jquery/1.3.2/HtmlJSJQuery.php';
require_once $localFilePath.'/../plugins/javascript/jquery/jquery-autogrow/1.2.2/HtmlJSJQueryAutoGrow.php';
require_once $localFilePath.'/../plugins/javascript/jquery/jquery-ui/1.7.2/HtmlJSJQueryUI.php';
require_once $localFilePath.'/../plugins/javascript/jquery/jqueryFileTree/1.01/HtmlJSJQueryFileTree.php';
require_once $localFilePath.'/../plugins/utils/common/getvars/1.0/tcm_utils.php';
require_once $localFilePath.'/../plugins/javascript/jit/1.1.2/HtmlJSJit.php';
require_once $localFilePath.'/../plugins/javascript/prototype/1.6.0.1/HtmlJSPrototype.php';
require_once $localFilePath.'/../plugins/utils/log/errorlog_logger/1.0/ErrorLogLogger.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserDaoException.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserServiceException.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/AuthenticationListenerInterface.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserInterface.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserWithMailInterface.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserDaoInterface.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/UserServiceInterface.php';
require_once $localFilePath.'/../plugins/security/userservice/1.0/MoufUserService.php';
require_once $localFilePath.'/../plugins/security/userservice-splash/1.0/Logged.php';
require_once $localFilePath.'/../plugins/security/userfiledao/1.0/UserFileBean.php';
require_once $localFilePath.'/../plugins/security/userfiledao/1.0/UserFileDaoException.php';
require_once $localFilePath.'/../plugins/security/userfiledao/1.0/UserFileDao.php';
require_once $localFilePath.'/../plugins/security/simplelogincontroller/1.0/SimpleLoginController.php';
require_once $localFilePath.'/../plugins/utils/cache/cache-interface/1.0/CacheInterface.php';
require_once $localFilePath.'/../plugins/utils/cache/file-cache/1.1/FileCache.php';

// User dependencies
require_once $localFilePath.'/validator/MoufValidatorService.php';
require_once $localFilePath.'/validator/MoufBasicValidationProvider.php';
require_once $localFilePath.'/controllers/DisplayPackageListInterface.php';
require_once $localFilePath.'/MoufSearchable.php';
require_once $localFilePath.'/MoufSearchService.php';
require_once $localFilePath.'/actions/MoufActionDescriptor.php';
require_once $localFilePath.'/actions/MoufActionProvider.php';
require_once $localFilePath.'/actions/DownloadPackageAction.php';
require_once $localFilePath.'/actions/EnablePackageAction.php';
require_once $localFilePath.'/actions/RedirectAction.php';
require_once $localFilePath.'/actions/MultiStepActionService.php';
require_once $localFilePath.'/actions/InstallController.php';
require_once $localFilePath.'/actions/MoufActionResultInterface.php';
require_once $localFilePath.'/actions/MoufActionRedirectResult.php';
require_once $localFilePath.'/actions/MoufActionDoneResult.php';
require_once $localFilePath.'/controllers/MoufController.php';
require_once $localFilePath.'/controllers/MoufRootController.php';
require_once $localFilePath.'/controllers/ComponentsController.php';
require_once $localFilePath.'/controllers/PackageController.php';
require_once $localFilePath.'/controllers/MoufInstanceController.php';
require_once $localFilePath.'/controllers/MoufDisplayGraphController.php';
require_once $localFilePath.'/controllers/ConfigController.php';
require_once $localFilePath.'/controllers/MoufValidatorController.php';
require_once $localFilePath.'/controllers/MoufLoginController.php';
require_once $localFilePath.'/controllers/PackageServiceController.php';
require_once $localFilePath.'/controllers/RepositorySourceController.php';
require_once $localFilePath.'/controllers/PackageDownloadController.php';
require_once $localFilePath.'/MoufPackageDownloadService.php';
require_once $localFilePath.'/MoufRepository.php';
require_once $localFilePath.'/controllers/PhpInfoController.php';
require_once $localFilePath.'/controllers/SearchController.php';
require_once $localFilePath.'/actions/InstallUtils.php';
require_once $localFilePath.'/load.php';

?>
