<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

// Packages dependencies
require_once dirname(__FILE__).'/../plugins/utils/log/log_interface/1.0/LogInterface.php';
require_once dirname(__FILE__).'/../plugins/html/htmlelement/1.0/Scopable.php';
require_once dirname(__FILE__).'/../plugins/html/htmlelement/1.0/HtmlElementInterface.php';
require_once dirname(__FILE__).'/../plugins/html/htmlelement/1.0/HtmlFromFile.php';
require_once dirname(__FILE__).'/../plugins/html/htmlelement/1.0/HtmlFromFunction.php';
require_once dirname(__FILE__).'/../plugins/html/htmlelement/1.0/HtmlString.php';
require_once dirname(__FILE__).'/../plugins/html/template/BaseTemplate/1.0/TemplateInterface.php';
require_once dirname(__FILE__).'/../plugins/html/template/BaseTemplate/1.0/BaseTemplate.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/1.0/models/Splash.php';
require_once dirname(__FILE__).'/../plugins/html/template/SplashTemplate/1.0/SplashTemplate.php';
require_once dirname(__FILE__).'/../plugins/html/template/SplashTemplate/1.0/SplashMenu.php';
require_once dirname(__FILE__).'/../plugins/html/template/SplashTemplate/1.0/SplashMenuItem.php';

// User dependencies
require_once dirname(__FILE__).'/../plugins/utils/common/getvars/1.0/tcm_utils.php';
require_once dirname(__FILE__).'/../plugins/javascript/prototype/1.6.0.1/HtmlJSPrototype.php';
require_once dirname(__FILE__).'/../plugins/javascript/jit/1.1.2/HtmlJSJit.php';
require_once dirname(__FILE__).'/../plugins/javascript/jquery/jquery/1.3.2/HtmlJSJQuery.php';
require_once dirname(__FILE__).'/../plugins/javascript/jquery/jquery-ui/1.7.2/HtmlJSJQueryUI.php';
require_once dirname(__FILE__).'/../plugins/javascript/jquery/jqueryFileTree/1.01/HtmlJSJQueryFileTree.php';
require_once dirname(__FILE__).'/../plugins/mvc/splash/1.0/models/Splash.php';
require_once dirname(__FILE__).'/../plugins/utils/log/errorlog_logger/1.0/ErrorLogLogger.php';
require_once dirname(__FILE__).'/controllers/MoufController.php';
require_once dirname(__FILE__).'/controllers/MoufRootController.php';
require_once dirname(__FILE__).'/controllers/ComponentsController.php';
require_once dirname(__FILE__).'/controllers/PackageController.php';

?>
