<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */

require_once dirname(__FILE__).'/../plugins/mvc/splash/1.0/SplashAdmin.php';
?>
