<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
require_once 'MoufManager.php';
MoufManager::initMoufManager();

MoufManager::getMoufManager()->registerComponent('../plugins/utils/common/getvars/1.0/tcm_utils.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/htmlelement/1.0/Scopable.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/htmlelement/1.0/HtmlFromFile.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/htmlelement/1.0/HtmlFromFunction.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/htmlelement/1.0/HtmlString.php');
MoufManager::getMoufManager()->registerComponent('../plugins/javascript/prototype/1.6.0.1/HtmlJSPrototype.php');
MoufManager::getMoufManager()->registerComponent('../plugins/javascript/jit/1.1.2/HtmlJSJit.php');
MoufManager::getMoufManager()->registerComponent('../plugins/javascript/jquery/jquery/1.3.2/HtmlJSJQuery.php');
MoufManager::getMoufManager()->registerComponent('../plugins/javascript/jquery/jquery-ui/1.7.2/HtmlJSJQueryUI.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/template/SplashTemplate/1.0/SplashMenu.php');
MoufManager::getMoufManager()->registerComponent('../plugins/html/template/SplashTemplate/1.0/SplashMenuItem.php');
MoufManager::getMoufManager()->registerComponent('../plugins/mvc/splash/1.0/models/Splash.php');
MoufManager::getMoufManager()->registerComponent('../plugins/mvc/splash/1.0/models/TemplateInterface.php');
MoufManager::getMoufManager()->registerComponent('../plugins/mvc/splash/1.0/themes/Splash/SplashTemplate.php');
MoufManager::getMoufManager()->registerComponent('../plugins/utils/log/errorlog_logger/ErrorLogLogger.php');
MoufManager::getMoufManager()->registerComponent('controllers/MoufController.php');
MoufManager::getMoufManager()->registerComponent('controllers/MoufRootController.php');

MoufManager::getMoufManager()->declareComponent('splash', 'Splash');
MoufManager::getMoufManager()->declareComponent('splashTemplate', 'SplashTemplate');
MoufManager::getMoufManager()->declareComponent('errorLogger', 'ErrorLogLogger');
MoufManager::getMoufManager()->declareComponent('mouf', 'MoufController');
MoufManager::getMoufManager()->declareComponent('moufTemplate', 'SplashTemplate');
MoufManager::getMoufManager()->declareComponent('prototype', 'HtmlJSPrototype');
MoufManager::getMoufManager()->declareComponent('newInstanceMenuItem', 'SplashMenuItem');
MoufManager::getMoufManager()->declareComponent('actionMenu', 'SplashMenu');
MoufManager::getMoufManager()->declareComponent('viewInstancesMenuItem', 'SplashMenuItem');
MoufManager::getMoufManager()->declareComponent('rootController', 'MoufRootController');
MoufManager::getMoufManager()->declareComponent('jQuery', 'HtmlJSJQuery');
MoufManager::getMoufManager()->declareComponent('jqueryui', 'HtmlJSJQueryUI');
MoufManager::getMoufManager()->declareComponent('componentsLabelMenuItem', 'SplashMenuItem');
MoufManager::getMoufManager()->declareComponent('packagesLabelMenuItem', 'SplashMenuItem');
MoufManager::getMoufManager()->declareComponent('managePackagesMenuItem', 'SplashMenuItem');

MoufManager::getMoufManager()->setParameter('moufTemplate', 'title', 'Mouf - Build your website');
MoufManager::getMoufManager()->setParameter('moufTemplate', 'logoImg', 'mouf/views/images/MoufLogo.png');
MoufManager::getMoufManager()->setParameter('moufTemplate', 'css_files', array (
  0 => 'mouf/views/styles.css',
));
MoufManager::getMoufManager()->setParameter('newInstanceMenuItem', 'menuText', 'Create a new instance');
MoufManager::getMoufManager()->setParameter('newInstanceMenuItem', 'menuLink', 'mouf/mouf/newInstance');
MoufManager::getMoufManager()->setParameter('newInstanceMenuItem', 'menuCssClass', '');
MoufManager::getMoufManager()->setParameter('newInstanceMenuItem', 'propagatedUrlParameters', array (
  0 => 'selfedit',
));
MoufManager::getMoufManager()->setParameter('viewInstancesMenuItem', 'menuText', 'View declared instances');
MoufManager::getMoufManager()->setParameter('viewInstancesMenuItem', 'menuLink', 'mouf/mouf/');
MoufManager::getMoufManager()->setParameter('viewInstancesMenuItem', 'menuCssClass', '');
MoufManager::getMoufManager()->setParameter('viewInstancesMenuItem', 'propagatedUrlParameters', array (
  0 => 'selfedit',
));
MoufManager::getMoufManager()->setParameter('splashTemplate', 'logoImg', '');
MoufManager::getMoufManager()->setParameter('splashTemplate', 'title', 'Mouf - Your website');
MoufManager::getMoufManager()->setParameter('jQuery', 'noConflictMode', true);
MoufManager::getMoufManager()->setParameter('componentsLabelMenuItem', 'menuText', '<b>Components</b>');
MoufManager::getMoufManager()->setParameter('componentsLabelMenuItem', 'menuLink', '');
MoufManager::getMoufManager()->setParameter('componentsLabelMenuItem', 'menuCssClass', '');
MoufManager::getMoufManager()->setParameter('componentsLabelMenuItem', 'propagatedUrlParameters', false);
MoufManager::getMoufManager()->setParameter('packagesLabelMenuItem', 'menuText', '<b>Packages</b>');
MoufManager::getMoufManager()->setParameter('packagesLabelMenuItem', 'menuLink', '');
MoufManager::getMoufManager()->setParameter('packagesLabelMenuItem', 'menuCssClass', '');
MoufManager::getMoufManager()->setParameter('packagesLabelMenuItem', 'propagatedUrlParameters', false);
MoufManager::getMoufManager()->setParameter('managePackagesMenuItem', 'menuText', 'Enable/disable packages');
MoufManager::getMoufManager()->setParameter('managePackagesMenuItem', 'menuLink', 'mouf/packages');
MoufManager::getMoufManager()->setParameter('managePackagesMenuItem', 'menuCssClass', '');
MoufManager::getMoufManager()->setParameter('managePackagesMenuItem', 'propagatedUrlParameters', array (
  0 => 'selfedit',
));

MoufManager::getMoufManager()->bindComponents('splash', 'log', 'errorLogger');
MoufManager::getMoufManager()->bindComponents('splash', 'defaultTemplate', 'splashTemplate');
MoufManager::getMoufManager()->bindComponents('mouf', 'template', 'moufTemplate');
MoufManager::getMoufManager()->bindComponent('moufTemplate', 'head', array (
  0 => 'prototype',
  1 => 'jQuery',
  2 => 'jqueryui',
));
MoufManager::getMoufManager()->bindComponent('moufTemplate', 'left', array (
  0 => 'actionMenu',
));
MoufManager::getMoufManager()->bindComponent('actionMenu', 'menuItems', array (
  0 => 'packagesLabelMenuItem',
  1 => 'managePackagesMenuItem',
  2 => 'componentsLabelMenuItem',
  3 => 'viewInstancesMenuItem',
  4 => 'newInstanceMenuItem',
));
MoufManager::getMoufManager()->bindComponent('splashTemplate', 'head', array (
  0 => 'prototype',
));

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class MoufAdmin {
	/**
	 * @return Splash
	 */
	 public function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public function getSplashTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('splashTemplate');
	 }

	/**
	 * @return ErrorLogLogger
	 */
	 public function getErrorLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogger');
	 }

	/**
	 * @return MoufController
	 */
	 public function getMouf() {
	 	return MoufManager::getMoufManager()->getInstance('mouf');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public function getMoufTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate');
	 }

	/**
	 * @return HtmlJSPrototype
	 */
	 public function getPrototype() {
	 	return MoufManager::getMoufManager()->getInstance('prototype');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public function getNewInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('newInstanceMenuItem');
	 }

	/**
	 * @return SplashMenu
	 */
	 public function getActionMenu() {
	 	return MoufManager::getMoufManager()->getInstance('actionMenu');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public function getViewInstancesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewInstancesMenuItem');
	 }

	/**
	 * @return MoufRootController
	 */
	 public function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public function getJQuery() {
	 	return MoufManager::getMoufManager()->getInstance('jQuery');
	 }

	/**
	 * @return HtmlJSJQueryUI
	 */
	 public function getJqueryui() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryui');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public function getComponentsLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('componentsLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public function getPackagesLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('packagesLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public function getManagePackagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('managePackagesMenuItem');
	 }

}
?>
