<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
require_once 'MoufManager.php';
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'ACT_AS_REPOSITORY' => 
  array (
    'defaultValue' => false,
    'type' => 'bool',
    'comment' => 'If you set this variable to true, your Mouf installation will act as a repository: it will allow other Mouf installations to download any package available.
By default, this is behaviour is disabled.',
  ),
));

$moufManager->addPackageByXmlFile('utils/log/log_interface/1.0/package.xml');
$moufManager->addPackageByXmlFile('html/htmlelement/1.0/package.xml');
$moufManager->addPackageByXmlFile('html/template/BaseTemplate/1.0/package.xml');
$moufManager->addPackageByXmlFile('html/template/SplashTemplate/1.0/package.xml');
$moufManager->addPackageByXmlFile('utils/i18n/fine/1.0/package.xml');
$moufManager->addPackageByXmlFile('mvc/splash/1.0/package.xml');
$moufManager->addPackageByXmlFile('javascript/jquery/jquery/1.3.2/package.xml');
$moufManager->addPackageByXmlFile('javascript/jquery/jquery-autogrow/1.2.2/package.xml');
$moufManager->addPackageByXmlFile('javascript/jquery/jquery-ui/1.7.2/package.xml');
$moufManager->addPackageByXmlFile('javascript/jquery/jqueryFileTree/1.01/package.xml');
$moufManager->addPackageByXmlFile('utils/common/getvars/1.0/package.xml');
$moufManager->addPackageByXmlFile('javascript/jit/1.1.2/package.xml');
$moufManager->addPackageByXmlFile('javascript/prototype/1.6.0.1/package.xml');
$moufManager->addPackageByXmlFile('utils/log/errorlog_logger/1.0/package.xml');
$moufManager->addPackageByXmlFile('security/userservice/1.0/package.xml');
$moufManager->addPackageByXmlFile('security/userservice-splash/1.0/package.xml');
$moufManager->addPackageByXmlFile('security/userfiledao/1.0/package.xml');
$moufManager->addPackageByXmlFile('security/simplelogincontroller/1.0/package.xml');

require dirname(__FILE__).'/../plugins/mvc/splash/1.0/SplashExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery/1.3.2/JQueryExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery-autogrow/1.2.2/JQueryAutoGrowExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jquery-ui/1.7.2/JQueryUIExternalComponent.php';
require dirname(__FILE__).'/../plugins/javascript/jquery/jqueryFileTree/1.01/JQueryFileTreeExternalComponent.php';

$moufManager->addComponentInstances(array (
  'splash' => 
  array (
    'class' => 'Splash',
    'external' => false,
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'defaultTemplate' => 'splashTemplate',
    ),
  ),
  'splashTemplate' => 
  array (
    'class' => 'SplashTemplate',
    'external' => false,
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'prototype',
      ),
    ),
    'fieldProperties' => 
    array (
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'errorLogger' => 
  array (
    'class' => 'ErrorLogLogger',
    'external' => false,
  ),
  'mouf' => 
  array (
    'class' => 'MoufController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'moufTemplate' => 
  array (
    'class' => 'SplashTemplate',
    'external' => false,
    'fieldProperties' => 
    array (
      'title' => 
      array (
        'value' => 'Mouf - Build your website',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoImg' => 
      array (
        'value' => 'mouf/views/images/MoufLogo.png',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'css_files' => 
      array (
        'value' => 
        array (
          0 => 'mouf/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'head' => 
      array (
        0 => 'prototype',
        1 => 'jQuery',
        2 => 'jqueryui',
        3 => 'jqueryFileTree',
        4 => 'jquery-autogrow-1.2.2',
      ),
      'left' => 
      array (
        0 => 'actionMenu',
      ),
    ),
  ),
  'prototype' => 
  array (
    'class' => 'HtmlJSPrototype',
    'external' => false,
  ),
  'newInstanceMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Create a new instance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/mouf/newInstance',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'actionMenu' => 
  array (
    'class' => 'SplashMenu',
    'external' => false,
    'fieldBinds' => 
    array (
      'menuItems' => 
      array (
        0 => 'selfAnalysisLabelMenu',
        1 => 'moufStatusMenuItem',
        2 => 'packagesLabelMenuItem',
        3 => 'managePackagesMenuItem',
        4 => 'configLabelMenuItem',
        5 => 'editConfigMenuItem',
        6 => 'componentsLabelMenuItem',
        7 => 'loadComponentsMenuItem',
        8 => 'viewInstancesMenuItem',
        9 => 'newInstanceMenuItem',
        10 => 'miscellaneousLabelMenuItem',
        11 => 'logoutMenuItem',
      ),
    ),
  ),
  'viewInstancesMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'View declared instances',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => 'MoufRootController',
    'external' => false,
  ),
  'jQuery' => 
  array (
    'class' => 'HtmlJSJQuery',
    'external' => false,
    'fieldProperties' => 
    array (
      'noConflictMode' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jqueryui' => 
  array (
    'class' => 'HtmlJSJQueryUI',
    'external' => false,
  ),
  'componentsLabelMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => '<b>Components</b>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesLabelMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => '<b>Packages</b>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'managePackagesMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Enable/disable packages',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/packages/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'loadComponentsMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Include PHP files',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/components/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'components' => 
  array (
    'class' => 'ComponentsController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'jqueryFileTree' => 
  array (
    'class' => 'HtmlJSJQueryFileTree',
    'external' => false,
  ),
  'packages' => 
  array (
    'class' => 'PackageController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'instance' => 
  array (
    'class' => 'MoufInstanceController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'displayGraph' => 
  array (
    'class' => 'MoufDisplayGraphController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'config' => 
  array (
    'class' => 'ConfigController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
    ),
  ),
  'configLabelMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => '<b>Configuration</b>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'editConfigMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Edit configuration',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/config/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validate' => 
  array (
    'class' => 'MoufValidatorController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'moufTemplate',
      'validatorService' => 'validatorService',
    ),
  ),
  'validatorService' => 
  array (
    'class' => 'MoufValidatorService',
    'external' => false,
    'fieldBinds' => 
    array (
      'validators' => 
      array (
        0 => 'requiredFilesValidator',
        1 => 'configCompleteValidator',
      ),
    ),
  ),
  'requiredFilesValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Required files validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/required_files_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'selfAnalysisLabelMenu' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => '<b>Self-analysis</b>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'moufStatusMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Mouf status',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/validate/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'configCompleteValidator' => 
  array (
    'class' => 'MoufBasicValidationProvider',
    'external' => false,
    'fieldProperties' => 
    array (
      'name' => 
      array (
        'value' => 'Configuration file validator',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'url' => 
      array (
        'value' => 'mouf/direct/config_complete_validator.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userService' => 
  array (
    'class' => 'MoufUserService',
    'external' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogger',
      'userDao' => 'userFileDao',
    ),
    'fieldProperties' => 
    array (
      'loginPageUrl' => 
      array (
        'value' => 'mouf/login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'sessionPrefix' => 
      array (
        'value' => 'Mouf',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userFileDao' => 
  array (
    'class' => 'UserFileDao',
    'external' => false,
    'fieldProperties' => 
    array (
      'userFile' => 
      array (
        'value' => 'MoufUsers.php',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'miscellaneousLabelMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => '<b>Miscellaneous</b>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'logoutMenuItem' => 
  array (
    'class' => 'SplashMenuItem',
    'external' => false,
    'fieldProperties' => 
    array (
      'menuText' => 
      array (
        'value' => 'Logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuLink' => 
      array (
        'value' => 'mouf/login/logout',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'menuCssClass' => 
      array (
        'value' => '',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'propagatedUrlParameters' => 
      array (
        'value' => 
        array (
          0 => 'selfedit',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'login' => 
  array (
    'class' => 'MoufLoginController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'splashTemplate',
      'userService' => 'userService',
      'contentBeforeLoginBox' => 
      array (
        0 => 'loginWelcomeMessage',
      ),
    ),
    'fieldProperties' => 
    array (
      'defaultRedirectUrl' => 
      array (
        'value' => 'mouf/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'logoutRedirectUrl' => 
      array (
        'value' => 'mouf/login/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'passwordLabel' => 
      array (
        'value' => 'Password',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nPasswordLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'loginSubmitLabel' => 
      array (
        'value' => 'Login',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nLoginSubmitLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'badCredentialsLabel' => 
      array (
        'value' => 'Invalid login or password, please try again.',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'i18nBadCredentialsLabel' => 
      array (
        'value' => false,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'loginWelcomeMessage' => 
  array (
    'class' => 'HtmlString',
    'external' => false,
    'fieldProperties' => 
    array (
      'htmlString' => 
      array (
        'value' => '<h1>Login</h1>
<p>Welcome to Mouf. Please login to access the administration interface of your web application.</p>
<br/>
<br/>
<br/>',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesService' => 
  array (
    'class' => 'PackageServiceController',
    'external' => false,
  ),
));

$moufManager->registerComponent('validator/MoufValidatorService.php');
$moufManager->registerComponent('validator/MoufBasicValidationProvider.php');
$moufManager->registerComponent('controllers/MoufController.php');
$moufManager->registerComponent('controllers/MoufRootController.php');
$moufManager->registerComponent('controllers/ComponentsController.php');
$moufManager->registerComponent('controllers/PackageController.php');
$moufManager->registerComponent('controllers/MoufInstanceController.php');
$moufManager->registerComponent('controllers/MoufDisplayGraphController.php');
$moufManager->registerComponent('controllers/ConfigController.php');
$moufManager->registerComponent('controllers/MoufValidatorController.php');
$moufManager->registerComponent('controllers/MoufLoginController.php');
$moufManager->registerComponent('controllers/PackageServiceController.php');
$moufManager->registerComponent('load.php');

unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class MoufAdmin {
	/**
	 * @return Splash
	 */
	 public static function getSplash2() {
	 	return MoufManager::getMoufManager()->getInstance('splash2');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public static function getJquery1_3_2() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-1.3.2');
	 }

	/**
	 * @return HtmlJSJQueryAutoGrow
	 */
	 public static function getJqueryautogrow1_2_2() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-autogrow-1.2.2');
	 }

	/**
	 * @return HtmlJSJQueryUI
	 */
	 public static function getJqueryui1_7_2() {
	 	return MoufManager::getMoufManager()->getInstance('jquery-ui-1.7.2');
	 }

	/**
	 * @return HtmlJSJQueryFileTree
	 */
	 public static function getJqueryFileTree1_01() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryFileTree-1.01');
	 }

	/**
	 * @return Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getSplashTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('splashTemplate');
	 }

	/**
	 * @return ErrorLogLogger
	 */
	 public static function getErrorLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogger');
	 }

	/**
	 * @return MoufController
	 */
	 public static function getMouf() {
	 	return MoufManager::getMoufManager()->getInstance('mouf');
	 }

	/**
	 * @return SplashTemplate
	 */
	 public static function getMoufTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('moufTemplate');
	 }

	/**
	 * @return HtmlJSPrototype
	 */
	 public static function getPrototype() {
	 	return MoufManager::getMoufManager()->getInstance('prototype');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getNewInstanceMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('newInstanceMenuItem');
	 }

	/**
	 * @return SplashMenu
	 */
	 public static function getActionMenu() {
	 	return MoufManager::getMoufManager()->getInstance('actionMenu');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getViewInstancesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('viewInstancesMenuItem');
	 }

	/**
	 * @return MoufRootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return HtmlJSJQuery
	 */
	 public static function getJQuery() {
	 	return MoufManager::getMoufManager()->getInstance('jQuery');
	 }

	/**
	 * @return HtmlJSJQueryUI
	 */
	 public static function getJqueryui() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryui');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getComponentsLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('componentsLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getPackagesLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('packagesLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getManagePackagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('managePackagesMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getLoadComponentsMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('loadComponentsMenuItem');
	 }

	/**
	 * @return ComponentsController
	 */
	 public static function getComponents() {
	 	return MoufManager::getMoufManager()->getInstance('components');
	 }

	/**
	 * @return HtmlJSJQueryFileTree
	 */
	 public static function getJqueryFileTree() {
	 	return MoufManager::getMoufManager()->getInstance('jqueryFileTree');
	 }

	/**
	 * @return PackageController
	 */
	 public static function getPackages() {
	 	return MoufManager::getMoufManager()->getInstance('packages');
	 }

	/**
	 * @return MoufInstanceController
	 */
	 public static function getInstance() {
	 	return MoufManager::getMoufManager()->getInstance('instance');
	 }

	/**
	 * @return MoufDisplayGraphController
	 */
	 public static function getDisplayGraph() {
	 	return MoufManager::getMoufManager()->getInstance('displayGraph');
	 }

	/**
	 * @return ConfigController
	 */
	 public static function getConfig() {
	 	return MoufManager::getMoufManager()->getInstance('config');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getConfigLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('configLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getEditConfigMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('editConfigMenuItem');
	 }

	/**
	 * @return MoufValidatorController
	 */
	 public static function getValidate() {
	 	return MoufManager::getMoufManager()->getInstance('validate');
	 }

	/**
	 * @return MoufValidatorService
	 */
	 public static function getValidatorService() {
	 	return MoufManager::getMoufManager()->getInstance('validatorService');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getRequiredFilesValidator() {
	 	return MoufManager::getMoufManager()->getInstance('requiredFilesValidator');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getSelfAnalysisLabelMenu() {
	 	return MoufManager::getMoufManager()->getInstance('selfAnalysisLabelMenu');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getMoufStatusMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('moufStatusMenuItem');
	 }

	/**
	 * @return MoufBasicValidationProvider
	 */
	 public static function getConfigCompleteValidator() {
	 	return MoufManager::getMoufManager()->getInstance('configCompleteValidator');
	 }

	/**
	 * @return MoufUserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->getInstance('userService');
	 }

	/**
	 * @return UserFileDao
	 */
	 public static function getUserFileDao() {
	 	return MoufManager::getMoufManager()->getInstance('userFileDao');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getMiscellaneousLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('miscellaneousLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getLogoutMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('logoutMenuItem');
	 }

	/**
	 * @return MoufLoginController
	 */
	 public static function getLogin() {
	 	return MoufManager::getMoufManager()->getInstance('login');
	 }

	/**
	 * @return HtmlString
	 */
	 public static function getLoginWelcomeMessage() {
	 	return MoufManager::getMoufManager()->getInstance('loginWelcomeMessage');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getFineAdminLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('fineAdminLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getFineSupportedLanguagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('fineSupportedLanguagesMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getFineEnableDisableMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('fineEnableDisableMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getFineMissingLabelsMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('fineMissingLabelsMenuItem');
	 }

	/**
	 * @return EditLabelController
	 */
	 public static function getEditLabels() {
	 	return MoufManager::getMoufManager()->getInstance('editLabels');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getSplashAdminLabelMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('splashAdminLabelMenuItem');
	 }

	/**
	 * @return SplashMenuItem
	 */
	 public static function getSplashAdminApacheConfigItem() {
	 	return MoufManager::getMoufManager()->getInstance('splashAdminApacheConfigItem');
	 }

	/**
	 * @return SplashAdminApacheConfigureController
	 */
	 public static function getSplashApacheConfig() {
	 	return MoufManager::getMoufManager()->getInstance('splashApacheConfig');
	 }

	/**
	 * @return PackageServiceController
	 */
	 public static function getPackagesService() {
	 	return MoufManager::getMoufManager()->getInstance('packagesService');
	 }

}
?>
